### ISSUE TITLE
 Huawei Freebuds 4i freezing sound in the pocket

### ISSUE THREAD

**Issue by 2ne9dec** [TheLastGimbus/FreeBuddy#21]
Hello! After updating Huawei Freebuds 4i to version 1.9.0.0198, the headphones began to freeze the sound in my pocket jacket on the street; this did not happen with the previous version. The problem appeared after the update and on two pairs that are connected to different phones. I reset the headphones, the problem did not go away. You can reset the previous version of the firmware or tell me how to downgrade, since it is completely impossible to use.

**Comment by TheLastGimbus** [comment]
1. I have absolutely no connection to Huawei - don't work for them, don't have the buds code, etc (to be clear)
2. I didn't try to reverse engineer how headphones update firmware, and probably won't try since it's wayyy not worth the risks
3. ...nor do i collect old versions of the firmware

I cant help you, sorry for your headphones :(
