### ISSUE TITLE
Equaliser add functionality 

### ISSUE THREAD

**Issue by Pierochr** [TheLastGimbus/FreeBuddy#7]
Hi, it is possible to add equaliser functionality like bass, rock...

**Comment by TheLastGimbus** [comment]
Hi! (You're the guy from the review 😅?) This app is ment to just control headphones, monitor their battery, etc - unless some models will have equalizers *inside* them, I'm not gonna add system (android) equalizer because i have no idea about this, and there are plantey of great ones already, like Wavelet: https://play.google.com/store/apps/details?id=com.pittvandewitt.wavelet&hl=en&gl=US
